version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
    environment:
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
      - "POSTGRES_DB=postgres"
    ports:
      - "5432:5432"
  bowling:
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080